/** Large-cap US universe — random subset picked each day for the scan. */
export const BIG_STOCKS = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "GOOGL", name: "Alphabet" },
  { symbol: "GOOG", name: "Alphabet C" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "META", name: "Meta" },
  { symbol: "BRK-B", name: "Berkshire" },
  { symbol: "LLY", name: "Eli Lilly" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "JPM", name: "JPMorgan" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "V", name: "Visa" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "XOM", name: "Exxon Mobil" },
  { symbol: "UNH", name: "UnitedHealth" },
  { symbol: "COST", name: "Costco" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "CVX", name: "Chevron" },
  { symbol: "MRK", name: "Merck" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "LIN", name: "Linde" },
  { symbol: "TMO", name: "Thermo Fisher" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "ACN", name: "Accenture" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "ABT", name: "Abbott" },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "CAT", name: "Caterpillar" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "AMAT", name: "Applied Materials" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "BKNG", name: "Booking" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "DE", name: "Deere" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "T", name: "AT&T" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "GILD", name: "Gilead" },
  { symbol: "MU", name: "Micron" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "SYK", name: "Stryker" },
  { symbol: "MDT", name: "Medtronic" },
  { symbol: "PLTR", name: "Palantir" },
  { symbol: "SHOP", name: "Shopify" },
  { symbol: "XYZ", name: "Block" },
  { symbol: "SNOW", name: "Snowflake" },
  { symbol: "COIN", name: "Coinbase" },
  { symbol: "RTX", name: "RTX" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "PM", name: "Philip Morris" },
  { symbol: "UNP", name: "Union Pacific" },
  { symbol: "TJX", name: "TJX" },
  { symbol: "CMCSA", name: "Comcast" },
  { symbol: "PGR", name: "Progressive" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "DHR", name: "Danaher" },
  { symbol: "VRTX", name: "Vertex" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "ETN", name: "Eaton" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "KLAC", name: "KLA" },
  { symbol: "MMC", name: "Marsh & McLennan" },
  { symbol: "CB", name: "Chubb" },
  { symbol: "SO", name: "Southern Co" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "MO", name: "Altria" },
  { symbol: "FI", name: "Fiserv" },
  { symbol: "BMY", name: "Bristol-Myers" },
  { symbol: "REGN", name: "Regeneron" },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "ZTS", name: "Zoetis" },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "CL", name: "Colgate-Palmolive" },
  { symbol: "SNPS", name: "Synopsys" },
  { symbol: "CDNS", name: "Cadence" },
  { symbol: "WM", name: "Waste Management" },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "MCO", name: "Moody's" },
  { symbol: "PH", name: "Parker-Hannifin" },
  { symbol: "USB", name: "US Bancorp" },
  { symbol: "PNC", name: "PNC Financial" },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "SLB", name: "Schlumberger" },
  { symbol: "MCK", name: "McKesson" },
  { symbol: "CI", name: "Cigna" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "F", name: "Ford" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "ABNB", name: "Airbnb" },
  { symbol: "MAR", name: "Marriott" },
  { symbol: "ORLY", name: "O'Reilly Auto" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "ADP", name: "ADP" },
  { symbol: "EMR", name: "Emerson" },
  { symbol: "CME", name: "CME Group" },
  { symbol: "NSC", name: "Norfolk Southern" },
  { symbol: "FDX", name: "FedEx" },
  { symbol: "UPS", name: "UPS" },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "NOC", name: "Northrop Grumman" },
  { symbol: "LMT", name: "Lockheed Martin" },
  { symbol: "GD", name: "General Dynamics" },
  { symbol: "BA", name: "Boeing" },
  { symbol: "MSI", name: "Motorola Solutions" },
  { symbol: "APH", name: "Amphenol" },
  { symbol: "CMG", name: "Chipotle" },
  { symbol: "ECL", name: "Ecolab" },
  { symbol: "AJG", name: "Arthur J Gallagher" },
  { symbol: "AON", name: "Aon" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "HLT", name: "Hilton" },
  { symbol: "TGT", name: "Target" },
  { symbol: "KMB", name: "Kimberly-Clark" },
  { symbol: "SRE", name: "Sempra" },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "O", name: "Realty Income" },
  { symbol: "CCI", name: "Crown Castle" },
  { symbol: "APD", name: "Air Products" },
  { symbol: "FCX", name: "Freeport-McMoRan" },
  { symbol: "NEM", name: "Newmont" },
  { symbol: "DELL", name: "Dell" },
  { symbol: "CRWD", name: "CrowdStrike" },
  { symbol: "MRVL", name: "Marvell" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "WDAY", name: "Workday" },
  { symbol: "ADSK", name: "Autodesk" },
  { symbol: "ROP", name: "Roper" },
  { symbol: "NXPI", name: "NXP Semiconductors" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "EXC", name: "Exelon" },
  { symbol: "KDP", name: "Keurig Dr Pepper" },
  { symbol: "GIS", name: "General Mills" },
  { symbol: "KHC", name: "Kraft Heinz" },
  { symbol: "YUM", name: "Yum Brands" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "DG", name: "Dollar General" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "FAST", name: "Fastenal" },
  { symbol: "CTAS", name: "Cintas" },
  { symbol: "PAYX", name: "Paychex" },
  { symbol: "VRSK", name: "Verisk" },
  { symbol: "IDXX", name: "Idexx Labs" },
  { symbol: "DXCM", name: "Dexcom" },
  { symbol: "BIIB", name: "Biogen" },
  { symbol: "ILMN", name: "Illumina" },
  { symbol: "MRNA", name: "Moderna" },
  { symbol: "ON", name: "ON Semiconductor" },
  { symbol: "MCHP", name: "Microchip" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "DDOG", name: "Datadog" },
  { symbol: "ZS", name: "Zscaler" },
  { symbol: "TEAM", name: "Atlassian" },
  { symbol: "MDB", name: "MongoDB" },
  { symbol: "NET", name: "Cloudflare" },
  { symbol: "HUBS", name: "HubSpot" },
  { symbol: "TTD", name: "Trade Desk" },
  { symbol: "RBLX", name: "Roblox" },
  { symbol: "DKNG", name: "DraftKings" },
  { symbol: "RIVN", name: "Rivian" },
  { symbol: "LCID", name: "Lucid" },
  { symbol: "SOFI", name: "SoFi" },
  { symbol: "HOOD", name: "Robinhood" },
  { symbol: "ARM", name: "Arm Holdings" },
  { symbol: "SMCI", name: "Super Micro" },
  { symbol: "DASH", name: "DoorDash" },
  { symbol: "CAVA", name: "Cava Group" },
  { symbol: "DUOL", name: "Duolingo" },
];

export const BIG_STOCK_BY_SYMBOL = new Map(BIG_STOCKS.map((s) => [s.symbol, s]));

export const RANDOM_SCAN_COUNT = 55;

export function dailySeed() {
  const d = new Date();
  return d.getFullYear() * 10000 + (d.getMonth() + 1) * 100 + d.getDate();
}

export function seededShuffle(items, seed) {
  const arr = [...items];
  let state = seed >>> 0;

  const rng = () => {
    state = (Math.imul(1664525, state) + 1013904223) >>> 0;
    return state / 4294967296;
  };

  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

export function pickRandomBigStocks(excludeSymbols, count, seed = dailySeed()) {
  const exclude = new Set(excludeSymbols);
  const pool = BIG_STOCKS.filter((s) => !exclude.has(s.symbol));
  const shuffled = seededShuffle(pool, seed);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
